name: space_shooter_workshop
description: The start of a space shooter game for the FlutterCon 2023 workshop.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flame: ^1.13.1
  flame_audio: ^2.1.6
  flame_splash_screen: ^0.2.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^5.1.0

dev_dependencies:
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - google_fonts/
